export const AGGLOMERATE_HAS_ERRORED = 'AGGLOMERATE_HAS_ERRORED';
export const AGGLOMERATE_IS_LOADING = 'AGGLOMERATE_IS_LOADING';
export const AGGLOMERATE_FETCH_DATA_SUCCESS = 'AGGLOMERATE_FETCH_DATA_SUCCESS';
export const AGGLOMERATE_LIST_FETCH_DATA_SUCCESS = 'AGGLOMERATE_LIST_FETCH_DATA_SUCCESS';
